Add PATH outputs
FRBs/FRB pull request #123
Opened 2021-10-27 19:19 UTC by profxj

As titled, this PR includes the PATH estimates for FRB hosts.

Need to add tests and a bit of docs before merging.

2021-12-22 18:45 UTC, profxj commented
Tests now passing:

========== 59 passed, 1 skipped, 2224 warnings in 1157.66s (0:19:17) ==========

2022-01-14 17:05 UTC, tarraneh commented on docs/galaxies.rst
> +A subset of the FRB Host galaxies have been analyzed using
using >> using the

2022-01-21 15:32 UTC, tarraneh requested changes
Minor changes

2022-01-21 15:32 UTC, tarraneh commented on frb/builds/build_path.py
> +        tol (float, optional):  Tolearance for a match to the expected host
Tolearance >> Tolerance

2022-01-21 15:32 UTC, tarraneh commented on frb/builds/build_path.py
> +    # Parse optionsd
optionsd >> options

2022-01-21 15:32 UTC, tarraneh commented on frb/galaxies/utils.py
> +        pandas.DataFrame: Table of galaxy coordiantes and PATH results
coordinates

2022-01-25 15:19 UTC, profxj commented on frb/associate/frbassociate.py
> +        # Plate scale
done

2022-01-25 15:20 UTC, profxj commented on frb/galaxies/utils.py
> +        pandas.DataFrame: Table of galaxy coordiantes and PATH results
fixed

2022-01-25 15:33 UTC, profxj commented
============ 57 passed, 3 skipped, 31 warnings in 118.22s (0:01:58) ============

2022-01-25 17:35 UTC, profxj commented on frb/builds/build_path.py
> +        tol (float, optional):  Tolearance for a match to the expected host
fixed

2022-01-25 17:38 UTC, tarraneh approved these changes
All good

2022-01-25 18:56 UTC, profxj commented
Merging!

2022-01-25 18:56 UTC, merged