Add in Driver and a bit more
FRBs/FRB pull request #82
Opened 2020-11-16 15:47 UTC by profxj

As titled.

2020-11-18 16:11 UTC, tarraneh commented on frb/associate/chance.py
> +# Spline parameters(globals) are for rmag vs sigma
`#Spline parameters (globals) are for m_r vs sigma`

2020-11-18 16:22 UTC, tarraneh requested changes
Minor change to `driver_sigma()` function: use `rmag` instead of `m_r` for consistency.

2020-11-18 16:22 UTC, tarraneh commented on frb/associate/chance.py
> +def driver_sigma(m_r):
`def driver_sigma(rmag)`

2020-11-18 16:22 UTC, tarraneh commented on frb/associate/chance.py
> +        m_r (float or np.ndarray):
`rmag (float or np.ndarray)`

2020-11-18 16:22 UTC, tarraneh commented on frb/associate/chance.py
> +    return 10**driver_spl(m_r)
`return 10**driver_spl(rmag)`

2020-11-19 15:08 UTC, profxj commented on frb/associate/chance.py
> +def driver_sigma(m_r):
modified.

2020-11-19 15:08 UTC, profxj commented on frb/associate/chance.py
> +        m_r (float or np.ndarray):
same

2020-11-19 15:08 UTC, profxj commented on frb/associate/chance.py
> +    return 10**driver_spl(m_r)
done

2020-11-19 15:09 UTC, profxj commented
merging.

2020-11-19 15:09 UTC, merged