Flux conversions galore
FRBs/FRB pull request #98
Opened 2021-01-21 18:30 UTC by SunilSimha

The master branch needs some changes to make the flux conversions from mags less messy.

2021-01-23 14:24 UTC, profxj requested changes
just a minor nit

key question:  should we take the opportunity here to apply
this to all the FRB galaxies (hosts and foreground), i.e. 
update `build_hosts.py` and run it to re-create the JSON files?

2021-01-23 14:24 UTC, profxj commented on frb/surveys/catalog_utils.py
> +    try:
please avoid `try/except`

2021-01-24 02:00 UTC, SunilSimha commented
> just a minor nit
> 
> key question: should we take the opportunity here to apply
> this to all the FRB galaxies (hosts and foreground), i.e.
> update `build_hosts.py` and run it to re-create the JSON files?

I think it would be nice to do that. We can have separate columns for the flux measurements in mags and in mJy. That way, the user will find the mags intuitive while also having no ambiguity with regards to the flux measurement. Alternatively, we can probably report the zero-point mags for each band.

2021-01-24 13:41 UTC, profxj commented
yeah, I like separate columns, even if it means 2x more
data in the file.  Do you want to take that on, or should
I do it?

2021-03-03 21:45 UTC, profxj commented
ok @SunilSimha -- I re-built the hosts.

Can you spot check a few before I merge?
Thanks

2021-03-04 18:09 UTC, SunilSimha commented
Fluxes look alright and the code seems to handle non-detections as expected. I think this is good to merge.

2021-03-04 18:25 UTC, profxj approved these changes
Time to merge!

2021-03-04 18:26 UTC, merged